<?php

/**
 * @file
 * Code for the Layout feature.
 */

include_once 'hr_layout.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function hr_layout_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('styles'))) {
    return "plugins/$plugin";
  }
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_block_info().
 */
function hr_layout_block_info() {
  return array(
    'hr_layout_login' => array(
      'info' => t('HR Login block'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function hr_layout_block_view($delta = '') {
  global $base_url;
  $block = array();

  switch ($delta) {
    case 'hr_layout_login':
      $block['content'] = '';
      if (!user_is_logged_in()) {
        if (module_exists('hid_auth')) {
          $block['content'] = l(t('Log in'), $base_url . '/connect/oauthconnector_hid_oauth', array(
            'attributes' => array(
              'class' => array(
                'btn',
                'btn-default',
              ),
            ),
            'query' => drupal_get_destination(),
          ));
        }
        else {
          $block['content'] = l(t('Log in'), 'login', array(
            'attributes' => array(
              'class' => array(
                'btn',
                'btn-default',
              ),
            ),
            'query' => drupal_get_destination(),
          ));
        }
      }
      break;

  }
  return $block;
}
