<?php

/**
 * @file
 * Code for the Pages feature.
 */

include_once 'hr_pages.features.inc';

/**
 * Implements hook_page_alter().
 *
 * Hide the sidebar when "hide vertical menu" is checked.
 */
function hr_pages_page_alter(&$page) {
  $node = menu_get_object();
  if ($node && $node->type == 'hr_page' && isset($node->field_page_menu[LANGUAGE_NONE]) && $node->field_page_menu[LANGUAGE_NONE][0]['value'] == 1) {
    unset($page['sidebar_first']);
  }
}
