<?php

/**
 * @file
 * Code for the Search feature.
 */

include_once 'hr_search.features.inc';

/**
 * Implements hook_facetapi_facet_info_alter().
 */
function hr_search_facetapi_facet_info_alter(array &$facet_info, array $searcher_info) {
  if (isset($facet_info['field_organizations'])) {
    $facet_info['field_organizations']['label'] = t('Organization');
  }

  if (isset($facet_info['field_asst_date:value'])) {
    $facet_info['field_asst_date:value']['label'] = t('Start date');
  }

  if (isset($facet_info['field_bundles:field_sector'])) {
    $facet_info['field_bundles:field_sector']['label'] = t('Global Cluster');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds chosen-disable class to search_api_sorts_widget.
 */
function hr_search_form_search_api_sorts_widget_form_alter(&$form, &$form_state) {
  $form['sort_by']['#attributes'] = array('class' => array('chosen-disable'));
}
